"""
Analysis Pipeline for SV benchmarking

Snakefile workflow dry run: snakemake --config -np

Run with each rule as a separate job, grouping truvari together: 
snakemake --jobs 10 --configfile config/pedigree.yaml --cluster "qsub -W group_list=group_name -A group_name -l walltime={resources.walltime_h}:00:00 -l mem={resources.mem_mb}MB -l nodes=1:ppn={threads} -M email@address.com" --keep-going --groups truvari=trugroup --group-components trugroup=10
"""

import glob
import re
import pathlib
import pandas as pd
import os
from typing import List
from pathlib import Path

## Pipeline working directory
pipeline_workdir = os.getcwd()

workflow.first_rule = "all"


configfile: "config/tool_versions.yaml"


SAMPLES = config["samples"]
CALLERS = config["callers"]

wildcard_constraints: 
    sample= "(?:" + "|".join(map(re.escape, SAMPLES)) + ")",
    caller= "(?:" + "|".join(map(re.escape, CALLERS)) + ")"


# do the manual post processes first
ruleorder: truvari_deletion_refine > truvari_refine > common_truvari_collapse > dysgu  >  octopus >  common_postprocess_finalize_raw > common_postprocess_finalize > cnvpytor_postprocess  > common_postprocess_zip > manta_calling > common_postprocess_index > postprocess > truvari_deletion > truvari 

# load rules
# -----------------------------------------------------
# callers
for caller in CALLERS:

    include: f"rules/callers/{caller}.smk"


# analysis
include: "rules/truvari.smk"
include: "rules/analysis.smk"


out_dir = config["output"]

def get_scratch_directory(
    subdirs: List[str], force_workdir_scratch: bool = False
) -> str:
    """
    Auxiliary function that returns the scratch directory location
    for a given rule.

    Arguments
    ---------
    subdirs: List[str]
        List of subdirectory names.
    force_workdir_scratch: bool
        If true, force the scratch directory inside of the
        working directory.
    """
    basedir = Path(pipeline_workdir).joinpath("scratch")
    if subdirs:
        for element in subdirs:
            basedir = basedir.joinpath(element)
    return basedir.as_posix()

# optional messages, log and error handling
onstart:
    print("\n--- Analysis started ---\n")


onsuccess:
    print("\n--- Workflow finished! ---\n")


onerror:
    print("\n--- An error occurred! ---\n")


localrules:
    common_postprocess_finalize_raw,
    common_postprocess_finalize,
    common_postprocess_zip,
    common_postprocess_index,


rule all:
    input:
        callers=expand(
            "{output}/callers/{caller}/{sample}.final.vcf.gz",
            output=config["output"],
            sample=SAMPLES,
            caller=CALLERS,
        ),
        stat_summary=config["output"] + "/truvari/stat_summary.png",
        vcf_summary=config["output"] + "/truvari/type-ignored/fig1_count_split_TP.Rds",
        upset_analysis=config["output"] + "/truvari/type-ignored/_upset-degreesort.png",
       # benchmark_summary=config["output"] + "/benchmarks/caller-summary.csv",
    default_target: True


## 01. General  ##
rule adjust_bam: 
    input: 
        dict=config["human_ref_dict"],
        bam=config["sample_path"] + "archive/" + "{sample}.bam"
    output: 
        bam=config["sample_path"] + "{sample}.bam",
    threads: 2
    resources:
        walltime_h=8,
        mem_mb=40*1024,
        mem_gb=40,
    shell: 
        """
        ml picard/3.3.0-Java-17
        java -jar $EBROOTPICARD/picard.jar ReorderSam I={input.bam} O={output.bam} SD={input.dict} 
        """

# converts bam to cram if missing any
rule bam_to_cram:
    input:
        bam=config["sample_path"] + "{sample}.bam",
        reference=config["reference"],
    output:
        cram=config["sample_path"] + "{sample}.cram",
        crai=config["sample_path"] + "{sample}.crai",
    threads: 1
    resources:
        walltime_h=2,
        mem_mb=16000,
    log:
        config["output"] + "/logs/bam-to-cram/{sample}.log",
    envmodules:
        "samtools/" + config["samtools_version"],
    shell:
        """

            samtools view {input.bam} -C -T {input.reference} -o {output.cram} > {log} 2>&1

            samtools index {output.cram} -c {output.crai} > {log} 2>&1

            """

# converts bam to cram if missing any
rule bam_index:
    input:
        bam=config["sample_path"] + "{sample}.bam",
    output:
        bai=config["sample_path"] + "{sample}.bam.bai",
    threads: 1
    resources:
        walltime_h=2,
        mem_mb=16000,
    log:
        config["output"] + "/logs/bam-index/{sample}.log",
    envmodules:
        "samtools/" + config["samtools_version"],
    shell:
        """
            samtools index {input.bam} -c {output.bai} > {log} 2>&1
        """


#rule sample_split:
#    input:
#        bam=config["sample_path"] + "{sample}.bam",
#        bam_bai=config["sample_path"] + "{sample}.bam.bai",
#        true_vcf=config["truth"],
#    output:
#        true_vcf=config["sample_path"] + "{sample}.vcf.gz",
#        true_vcf_tbi=config["sample_path"] + "{sample}.vcf.gz.tbi",
#    threads: 1
#    resources:
#        walltime_h=2,
#        mem_mb=4000,
#    envmodules:
#        "bcftools/" + config["bcftools_version"],
#    shell:
#        """
#
#        bcftools view {input.true_vcf} -s {wildcards.sample} -Wtbi -o {output.true_vcf} -Ov               
#
#        """


# creates a version of the truth set with only deletions for popdel
rule truth_del:
    input:
        config["sample_path"] + "{sample}.vcf.gz",
    output:
        config["sample_path"] + "{sample}_del.vcf.gz",
    threads: 1
    resources:
        walltime_h=2,
        mem_mb=4000,
    envmodules:
        "bcftools/" + config["bcftools_version"],
    shell:
        """

        bcftools filter -i "INFO/SVTYPE=='DEL'" {input} -o {output} -Oz

        bcftools index -t {output}

        """


# standard postprocessing for all callers. sorts and normalizes
rule common_postprocess_finalize:
    input:
        vcf=config["output"] + "/callers/{caller}/{sample}.vcf.gz",
        tbi=config["output"] + "/callers/{caller}/{sample}.vcf.gz.tbi",
        ref=config["reference"],
    output:
        sorted=temp(config["output"] + "/callers/{caller}/{sample}.sorted.vcf"),
        reheader=config["output"] + "/callers/{caller}/{sample}.reheader.vcf",
        norm=temp(config["output"] + "/callers/{caller}/{sample}.norm.vcf"),
    #   subvcf=temp(config["output"] + "/callers/{caller}/{sample}.subset.vcf"),
    threads: 1
    resources:
        walltime_h=2,
        mem_mb=4000,
    log:
        config["output"] + "/logs/{caller}/{sample}.final.log",
    envmodules:
        "bcftools/" + config["bcftools_version"],
    shell:
        """

        echo {wildcards.sample} > {wildcards.sample}.name

        bcftools reheader -f {input.ref}.fai {input.vcf} -o {output.norm} -s {wildcards.sample}.name > {log} 2>&1

        echo "Reheadered" >> {log}
        

        # Sorts the VCF just in case it isn't already 
        bcftools sort {output.norm} -o {output.sorted} >> {log} 2>&1

        # Warn about bad sites and fix them (recommended)

        # Split multiallic sites into biallelic records, required by truvari

        bcftools norm -f {input.ref} --check-ref ws -m- {output.sorted} -o {output.reheader} -Oz --threads {threads}  >> {log} 2>&1
        """


use rule common_postprocess_finalize as common_postprocess_finalize_raw with:
    input:
        vcf=config["output"] + "/callers/{caller}/{sample}.vcf",
        ref=config["reference"],


# collapses any possible duplicates for truvari comparison
rule common_truvari_collapse:
    input:
        vcf=config["output"] + "/callers/{caller}/{sample}.reheader.vcf.gz",
        tbi=config["output"] + "/callers/{caller}/{sample}.reheader.vcf.gz.tbi",
        bed = config["truvari_bed"], 
    output:
        tempvcf=config["output"] + "/callers/{caller}/{sample}.final.vcf",
        collapsed=config["output"] + "/callers/{caller}/{sample}.collapse.vcf",
    log:
        config["output"] + "/logs/{caller}/{sample}.collapse.log",
    resources:
        mem_mb=8000,
        walltime_h=4,
    threads: 4
    envmodules:
        "truvari/" + config["truvari_version"],
        "bcftools/" + config["bcftools_version"],
    shell:
        """
        truvari collapse --bed {input.bed} -i {input.vcf} -o {output.tempvcf} --passonly -c {output.collapsed} >> {log} 2>&1
        """


# zips any vcf that needs it
rule common_postprocess_zip:
    input:
        config["output"] + "/callers/{caller}/{name}.vcf",
    priority: -10
    output:
        vcf=config["output"] + "/callers/{caller}/{name}.vcf.gz",
    threads: 1
    resources:
        walltime_h=2,
        mem_mb=4000,
    log:
        config["output"] + "/logs/{caller}/zip-{name}.log",
    envmodules:
        "bcftools/" + config["bcftools_version"],
    shell:
        """
        bcftools sort {input} -o {output.vcf} -Oz > {log} 2>&1
        """


# index any vcf that needs it
rule common_postprocess_index:
    input:
        config["output"] + "/callers/{caller}/{name}.vcf.gz",
    priority: -10
    output:
        tbi=config["output"] + "/callers/{caller}/{name}.vcf.gz.tbi",
    threads: 1
    resources:
        walltime_h=2,
        mem_mb=4000,
    log:
        config["output"] + "/logs/{caller}/index-{name}.log",
    envmodules:
        "bcftools/" + config["bcftools_version"],
    shell:
        """
        bcftools index -t {input} > {log} 2>&1 
        """


rule postprocess:
    input:
        ref_dict=config["human_ref_dict"],
        vcf=config["output"] + "/callers/{caller}/{sample}.vcf",
    output:
        sorted=temp(config["output"] + "/callers/{caller}/{sample}.{caller}_sorted.vcf"),
        header=temp(config["output"] + "/{caller}/{sample}.{caller}.header"),
        vcf=config["output"] + "/callers/{caller}/{sample}.vcf.gz",
        tbi=config["output"] + "/callers/{caller}/{sample}.vcf.gz.tbi",
    log:
        config["output"] + "/logs/{caller}/postprocess-{sample}.log",
    benchmark:
        config["output"] + "/benchmarks/{caller}/postprocess-{sample}.tsv"
    threads: 2
    resources:
        mem_gb=4,
        mem_mb=4000,
        walltime_h=4,
    envmodules:
        "HTSlib/" + config["htslib_version"],
        "bcftools/" + config["bcftools_version"],
        "Java/" + config["java_version"],
        "GATK/" + config["gatk_version"],
    shell:
        " gatk --java-options '-Xmx{resources.mem_gb}g' SortVcf "
        "     --INPUT {input.vcf} "
        "     --SEQUENCE_DICTIONARY {input.ref_dict} "
        "     --COMPRESSION_LEVEL 0 "
        "     --QUIET true "
        "     --CREATE_INDEX false "
        "     --OUTPUT {output.sorted}; "

        " INFO='##SVCommandLine=<ID={wildcards.caller},"
        'Date="\'$(date +"%b %d, %Y %r %Z")\'">\'; '

        ' bcftools view -h {output.sorted} | sed "\\$i $INFO" > {output.header}; '

        " bcftools reheader -h {output.header} {output.sorted} "

        " > {output.vcf}; "

        " tabix -p vcf {output.vcf}; "
        ") > {log} 2>&1 "
